### PR TITLE
Milestone 1: Setup project

### PR DESCRIPTION
**Pull request by bertil291utn**
# Calculator setup project files

### Please I'll be grateful if you send me some feedback about my project.

These were the tasks:
- Use create-react-app to initialize a new React app
  - Documentation: https://github.com/facebook/create-react-app
- Delete any unnecessary file or asset
- Add prop-types using npm for typechecking props.
- Add big.js using npm.
- Follow the instructions in create-react-app-buildpack to deploy the app to Heroku

This is the [project's repository](https://github.com/bertil291utn/restaurant-page/tree/feature/restaurant), live [demo](https://calculator-apk.herokuapp.com/) 
Thanks in advance 💻 🚀 🔥

### CODE REVIEW

**Comment by fatymahmed** [comment]
Friendly reminder: You should make sure that your repo looks professional before review.  
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/ and make sure that you have a descriptive readme file.   
You can use this [template](https://github.com/microverseinc/readme-template) as a guide.
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

Kindly note that you are required to have a descriptive readme file from the first milestone, it's under general requirements
readme

**Comment by bertil291utn** [comment]
## Forgot README file

- Sorry guys I forgot to add this file, now it's up to date

**Comment by bertil291utn** [comment]
## Forgot README file

- Sorry guys I forgot to add this file, now it's up to date

**Review by suretrust — APPROVED** [review]
Hi @bertil291utn, 👋

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your next milestone and happy coding!_ 🎉

**Pull request closed without merging**
